### ISSUE TITLE
issue in log file

### ISSUE THREAD

**Issue by robopassio** [gsutanto/smp_manifold_learning#1]
I check the log file ''smp_manifold_learning/plot/ecmnn/3Dsphere/normal/r00/log.txt'
and I got the following issue:
```
2021-04-10 10:30:45.670315: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
noise_level = 0.000000
DEVICE =  cpu
Traceback (most recent call last):
  File "train_ecmnn.py", line 469, in <module>
    N_local_neighborhood_mult=N_local_neighborhood_mult)
  File "train_ecmnn.py", line 171, in train_ecmnn
    aug_dataloader = pickle.load(aug_dataloader_input)
EOFError: Ran out of input
```
However, for the file: `../plot/ecmnn/3Dsphere/wo_augmentation//r00//log.txt` and `../plot/ecmnn/3Dsphere/wo_nspace_alignment//r00//log.txt`
It looks good:
```
2021-04-10 10:30:48.465790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

  0%|          | 0/5000 [00:00<?, ?it/s]
  3%|2         | 134/5000 [00:00<00:03, 1330.93it/s]
  5%|5         | 272/5000 [00:00<00:03, 1359.47it/s]
  8%|8         | 409/5000 [00:00<00:03, 1360.79it/s]
 11%|#         | 546/5000 [00:00<00:03, 1363.54it/s]
 14%|#3        | 683/5000 [00:00<00:03, 1364.09it/s]
 16%|#6        | 820/5000 [00:00<00:03, 1364.65it/s]
 19%|#9        | 958/5000 [00:00<00:02, 1367.45it/s]

...
```

How could I solve this problem?
Thanks.

**Comment by gsutanto** [comment]
Hi!
Thanks for checking out our code!
I vaguely remember that sometimes the experiment trial crashed due to some threading issue during data loading from one of the external library that we depend on. The issue usually doesn't repeat the next time you try it again. Can you try the same command again to see if it doesn't crash this time?
If it still crashes, can you please let me know the sequence of commands (as well as any specific parameters you chose, if any) that lead to the crash?
Thanks again!

**Comment by robopassio** [comment]
Hi @gsutanto,
Thanks for your prompt support.
I just ran the command 
```
smp_manifold_learning/scripts/run_ablation_test_ecmnn.bash
```
Then during trying to pick the best model in `'smp_manifold_learning/plot/ecmnn/3Dsphere/normal/r00/log.txt` as suggested in the README file. I checked the log file and recognized that problem.
The problem may be related to the pickle file saving/loading. However, it only happened with the 3Dshpere. Thus, I cannot trace the error.
Your paper is very interesting but it looks difficult for fresher.
Can you help to list a detailed step from training to validate your proposed method?
Thanks!

**Comment by gsutanto** [comment]
Hi @robopassio ,
Sorry for my late reply... I checked the code again, and it seems when the error happened, it is at:
https://github.com/gsutanto/smp_manifold_learning/blob/60ef8278942c784c8d3bcd0a09031475f80d96fb/smp_manifold_learning/scripts/train_ecmnn.py#L171
It seemed that it found the file `aug_dataloader_filepath`, but the pickle loading was failed, maybe due to something wrong with the file `aug_dataloader_filepath` (related: https://stackoverflow.com/questions/24791987/why-do-i-get-pickle-eoferror-ran-out-of-input-reading-an-empty-file ). I am suspecting that the file `aug_dataloader_filepath` was corrupt for some reason.
Could you try deleting _all_ the sub-directories under `../plot/ecmnn/` and repeat the process from scratch, to see if the error persists?
